<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGapUvK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGapUvK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGapUvK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGapUvK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPGapUvK\App_KernelDevDebugContainer([
    'container.build_hash' => 'PGapUvK',
    'container.build_id' => 'd4543f6b',
    'container.build_time' => 1643234394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGapUvK');
