<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGO6uADf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGO6uADf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGO6uADf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGO6uADf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGO6uADf\App_KernelDevDebugContainer([
    'container.build_hash' => 'GO6uADf',
    'container.build_id' => '2710ffd6',
    'container.build_time' => 1643235031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGO6uADf');
