App\Entity\User:
  attributes:
    id:
      groups: ['user']
    email:
      groups: ['user']
    firstname:
      groups: ['user']
    lastname:
      groups: ['user']
    birth_date:
      groups: ['user']
    created:
      groups: ['user']
    knowledgeAssignments:
      groups: ['user']
    yes:
      groups: ['user']

    