version: "3"

services:
  database:
    build:
      context: ./build/mysql
      args:
        db_version: ${DB_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql.${DB_VERSION}
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - "3306:3306"

  php:
    build:
      context: ./build/php
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php${PHP_VERSION}
    ports:
      - "${PHP_PORT}:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ../:/var/www/html
      - ./build/logs:/var/log/apache2
      - ./build/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - database
    extra_hosts:
      - "${PHP_HOST}:127.0.0.1"